# Generated by Django 2.2.10 on 2020-02-14 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_text', models.CharField(max_length=280)),
                ('date', models.DateTimeField(verbose_name='date')),
                ('candidate', models.CharField(max_length=100)),
                ('sentiment', models.DecimalField(decimal_places=2, max_digits=5)),
                ('when_searched_for', models.CharField(max_length=100)),
                ('ratio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('likes', models.IntegerField()),
                ('retweets', models.IntegerField()),
                ('replies', models.IntegerField()),
            ],
            options={
                'db_table': 'JanFeb',
            },
        ),
    ]
